from typing import Any

ABI_VERSION: int

def create_ring(n: int, q_hex: str, digit_bits: int) -> object: ...
def compile_key(ring: object, key: tuple[tuple[bytes, bytes], ...]) -> object: ...
def apply_key(key: object, poly: bytes) -> tuple[bytes, bytes]: ...
def ring_product(ring: object, lhs: bytes, rhs: bytes) -> bytes: ...
def multiply(
    ring: object, lhs: tuple[bytes, ...], rhs: tuple[bytes, ...] | None, t: int
) -> tuple[bytes, bytes, bytes]: ...
def rotate_rows(
    key: object, ciphertext: tuple[bytes, ...], exponent: int
) -> tuple[bytes, bytes]: ...
def hamming_tile(
    relin: object,
    query: tuple[bytes, ...],
    tile: tuple[bytes, ...],
    rotations: tuple[tuple[int, object], ...],
    mask: bytes,
    t: int,
) -> tuple[bytes, bytes]: ...
def ring_info(ring: object) -> dict[str, Any]: ...
def key_bytes(key: object) -> int: ...
