"""Opaque native private decoder; this API must stay on the trusted client."""

ABI_VERSION: int

def create_decoder(n: int, q: int, t: int, p0: int, p1: int, secret: bytes) -> object: ...
def decode_slots(context: object, c0: bytes, c1: bytes) -> bytes: ...
def close_decoder(context: object) -> None: ...
