from typing import Any

ABI_VERSION: int

def create_ring(
    n: int, q_hex: str, digit_bits: int, fast: bool = False, residue: bool = False,
    kernel_level: int = 0,
) -> object: ...
def compile_key(ring: object, key: tuple[tuple[bytes, bytes], ...]) -> object: ...
def apply_key(key: object, poly: bytes) -> tuple[bytes, bytes]: ...
def ring_product(ring: object, lhs: bytes, rhs: bytes) -> bytes: ...
def multiply(
    ring: object, lhs: tuple[bytes, ...], rhs: tuple[bytes, ...] | None, t: int
) -> tuple[bytes, bytes, bytes]: ...
def rotate_rows(
    key: object, ciphertext: tuple[bytes, ...], exponent: int
) -> tuple[bytes, bytes]: ...
def hamming_tile(
    relin: object,
    query: tuple[bytes, ...],
    tile: tuple[bytes, ...],
    rotations: tuple[tuple[int, object], ...],
    mask: bytes,
    t: int,
) -> tuple[bytes, bytes]: ...
def ring_info(ring: object) -> dict[str, Any]: ...
def key_bytes(key: object) -> int: ...
def profile_hamming_tile(*args: Any) -> tuple[tuple[bytes, bytes], dict[str, Any]]: ...
def create_server(
    relin: object, keys: tuple[tuple[int, object], ...], padded: int, t: int, target_hex: str
) -> object: ...
def packed_search(
    server: object,
    query: tuple[bytes, bytes],
    index: tuple[tuple[bytes, bytes], ...],
    count: int,
    compact: bool,
) -> list[tuple[bytes, bytes]]: ...
def profile_packed_search(*args: Any) -> tuple[list[tuple[bytes, bytes]], dict[str, Any]]: ...
def server_bytes(server: object) -> int: ...
def profile_call(callback: Any) -> tuple[Any, dict[str, Any]]: ...
