from typing import Any

ABI_VERSION: int

def available() -> bool: ...
def create_server(
    relin: object,
    keys: tuple[tuple[int, object], ...],
    padded: int,
    t: int,
    target_hex: str,
    kernel_level: int = 3,
    batch_tiles: int = 32,
) -> object: ...
def packed_search(
    server: object,
    query: tuple[bytes, bytes],
    index: tuple[tuple[bytes, bytes], ...],
    count: int,
    compact: bool,
) -> list[tuple[bytes, bytes]]: ...
def server_bytes(server: object) -> int: ...
def profile_packed_search(*args: Any) -> tuple[list[tuple[bytes, bytes]], dict[str, Any]]: ...
def prepare_index(server: object, index: tuple[tuple[bytes, bytes], ...], count: int) -> object: ...
def prepared_search(
    server: object, query: tuple[bytes, bytes], index: object, compact: bool
) -> list[tuple[bytes, bytes]]: ...
def profile_prepared_search(*args: Any) -> tuple[list[tuple[bytes, bytes]], dict[str, Any]]: ...
def index_bytes(index: object) -> int: ...
